### ISSUE TITLE
Error while generating PDF

### ISSUE THREAD

**Issue by karandhodi** [demisto/sane-reports#91] opened 2020-01-23 21:10 UTC
Hi, when I generate the PDF in quick successions sometimes it works but sometimes it generates just a blank page.

The error I get is:

Using PhantomJS version 2.1.1
Agent details: Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
reportsServer.js,templates/ctaTemplate_final.json,dist/test_ctaNew.pdf
HTML template was created: /home/karan/node_modules/sane-reports/dist//test_ctaNew.html
ReferenceError: Can't find variable: reportData

  file:///home/karan/node_modules/sane-reports/dist//app.js:80074
  file:///home/karan/node_modules/sane-reports/dist//app.js:20 in __webpack_require__
  file:///home/karan/node_modules/sane-reports/dist//app.js:63
Read report page status: success
ReferenceError: Can't find variable: reportType

  undefined:3
  :8
PDF report was generated successfully.

What could be the reason for this?

Thank you !

**Comment by Bars92** [comment] 2020-01-25 13:08
hello @karandhodi, i am unable to reproduce the error. Can you please share the command you used to generate the report?

In anyway, i would highly recommend to use [Chromium or Chrome as mentioned here](https://github.com/demisto/sane-reports#quick-start) since PhatomJS having stability issues and is [no longer maintained](https://github.com/ariya/phantomjs/issues/15344) 
Please let me know if i can assist farther.

**Comment by aviadl** [comment] 2020-01-25 17:46
Closing as invalid per @Bars92 comment

**Closed by aviadl** 2020-01-25 17:46 UTC
Labels: bug
